# Generated by Django 2.2.15 on 2020-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.CharField(choices=[('Ot', 'Other'), ('Sp', 'Space'), ('Te', 'Technology')], default='Ot', max_length=2),
        ),
    ]
